### ISSUE TITLE
Some suggestions about the console

### ISSUE THREAD

**Issue by hlassiege** [clun/ff4j-extra#1]
Hi,

I've tested the console and it don't work exactly the way I thought it was ^^

If I can make some suggestions, I would say that the standalone console should not be forced to be connected to another application. If ever I use a jdbc or mongo store, the standalone console could just modified the store. 

Am I right ?

**Comment by clun** [comment]
The standalone console will access : 
- The featureStore (mongo, jdbc) whatever 
- The event repository for monitoring purpose which could be customized
- The cache system (to be able to clear cache if relevant)
As a consequence i found more convenient to use the API. 

But.... you are right, the only requirement to define a FF4J bean pointing the database and it will work.

I could find a way to configure the standalone console this way.

**Comment by clun** [comment]
it's done for a while now... just closing.
