### ISSUE TITLE
Environement as Xml file 

### ISSUE THREAD

**Issue by nabilblk** [clun/ff4j-extra#2]
Hi Cedric , 

when we move into the xml bean mode : 
<connection id="env1" mode="bean" url="classpath:spring/applicationContext-env1.xml" />

There is still in the web.xml two spring file declared in the Web Context of spring : 
applicationContext-console.xml
applicationContext-security.xml

For the security file it's ok because it's contain the security confuiguration to access to the console . 

The applicationContext-console.xml is problematic for me because i found an FF4j cionfiguration into it . 

What's that is mean ? 
Why the console need this file as they will retreive the FF4j context from applicationContext-env1.xml . 

i am confused . 

Thanks in advance for the explanation

**Comment by clun** [comment]
need for this configuration anymore from 1.6 :)
